export const SET_CURRENT_SCENE = 'SET_CURRENT_SCENE';

export const END_RUNNING_SHOW = 'END_RUNNING_SHOW';

export const END_CURRENT_SCENE_TIME = 'END_CURRENT_SCENE_TIME';

export const END_CURRENT_SCENE = 'END_CURRENT_SCENE';

export const UPDATE_CURRENT_LOOP = 'UPDATE_CURRENT_LOOP';

export const ADD_SCENES = 'ADD_SCENES';