export const FETCHED_MEDIA_EVENTS = 'FETCHED_MEDIA_EVENTS';

export const FETCHED_MEDIA_SECTOR = 'FETCHED_MEDIA_SECTOR';

export const FETCHED_MEDIA_JOBS = 'FETCHED_MEDIA_JOBS';

export const CREATE_NEW_JOB = 'CREATE_NEW_JOB';

export const FETCHED_MEDIA_TOOLS = 'FETCHED_MEDIA_TOOLS';

